verbose logging
Signed-off-by: Abhay Pratap Singh <psabhay@gmail.com>

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -22,27 +22,55 @@ INDEX=$4
 BIN_TEMP="/tmp/node_build_only"
 
 
+echo "Downloading node binaries.."
 curl -s https://nodejs.org/dist/v14.18.0/node-v14.18.0-linux-x64.tar.xz | tar zxv -C "$BIN_TEMP/node14" &> /dev/null
 if [[ $? != 0 ]] ; then
     echo "Could not download node binaries"
     exit 1
 fi
+echo "node binaries are download successfully."
 
 # Put node binaries in the PATH
 export PATH="$PATH:$BIN_TEMP/node14/bin"
+echo "Get the node version"
+node --version
+
+echo "Get the npm version"
+npm --version
+
 
 # make a directory in cache for building the build the react app
 NEW_APP_BASE="$CACHE_DIR/node_build_only/base"
+echo "Creating a new temp folder for app in cache dir - $NEW_APP_BASE"
 mkdir -p $NEW_APP_BASE
+if [[ $? != 0 ]] ; then
+    echo "Failed to create $NEW_APP_BASE"
+    exit 1
+fi
+
 
 # Now copy build directory content into the new app base directory
-cp -r "$BUILD_DIR/*" $NEW_APP_BASE
+echo "Show BUILD_DIR conten"
+ls -lah $BUILD_DIR
+
+echo "Copy BUILD_DIR contents to $NEW_APP_BASE"
+cp -rv "$BUILD_DIR/*" $NEW_APP_BASE
+if [[ $? != 0 ]] ; then
+    echo "Failed to copy BUILD_DIR to $NEW_APP_BASE"
+    exit 1
+fi
 
 # now change to the new app base and run build
+echo "Change directory to NEW_APP_BASE"
 cd $NEW_APP_BASE
+
+echo "show content to NEW_APP_BASE"
+ls -lah $NEW_APP_BASE
+
+echo "Run npm install and then build"
 npm install && npm run build
 
 # Now finally move the content of new app base into the build dir back
-mv "$NEW_APP_BASE/*" $BUILD_DIR/
+# mv "$NEW_APP_BASE/*" $BUILD_DIR/
 
 
